# Generated by Django 4.2 on 2025-07-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
