# Generated by Django 4.2 on 2025-07-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
